apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: frank2-example4
  labels:
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/auto-configure-actuators: "true"
    app.kubernetes.io/part-of: frank2-example4
spec:
  env:
    - name: JAVA_TOOL_OPTIONS
      value: "-Dlog.dir=/tmp -Dinstance.name=Frank2Example4 -Ddtap.stage=LOC"
  build:
    env:
      - name: BP_JVM_VERSION
        value: "17"
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  source:
    git:
      url: https://github.com/nevenc/frank-runner
      ref:
        branch: master
    subPath: examples/Frank2Example4
